# Generated by Django 4.1.2 on 2022-12-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_alter_home_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='cvv',
            new_name='Cvv',
        ),
    ]
