# Generated by Django 4.1.2 on 2022-12-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_rename_cvv_home_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='Cvv',
            field=models.CharField(max_length=3),
        ),
    ]
